name: etherpad-lite
vendor: Alexander Sack <asac@canonical.com>
architecture: amd64
icon: meta/go.svg
version: 1.0
services:
 - name: etherpad-lite
   description: "snappy etherpad-lite"
   start: helper/start
ports:
 required: 80

